### ISSUE TITLE
this.fileData.shortcuts.push is not a function

### ISSUE THREAD

**Issue by snackerfork** [doZennn/steam-rom-manager#284]
SRM version: 2.3.29
Operating System: Linux 5.13

Trying to use Emudeck on SteamOS and I'm having a bizarre issue I haven't been able to find any solution for. Whenever I attempt to save the app list, I get a "Fatal error in preview" alert, and my log says the following, even though Steam is closed (I always check task manager to be sure, Steam is not running in the background.)

"Cannot make changes while Steam while Steam is running!
Fatal error occurred in Preview. See event log for details.
Fatal Preview Error Error: Could not merge entries. TypeError: this.Filedata.shortcuts.push is not a function"

I've tried:

- Deleting config.vdf
- Deleting the leveldb folder.
- Restarting the Steam Deck, including after deleting the leveldb folder.
- Removing all added app entries, which does nothing and displays "Saving added category information to localconfig.vdf" indefinitely. Sometimes it displays "Category error (shortcuts and artwork will still be added): Key not found in database [_https://steamloopback.host▯U32938953-cloud-storage-namespaces]" but I don't know what this means or how to fix it.
- Deleting SRM and redownloading it through Emudeck.
- Redownloading custom variables/presets and using those presets to set up the parsers instead.

I have no idea what the problem could be. It seems like it might be a permissions error and it thinks the file is read-only, but I don't understand what file that is or what it needs to be set to.

**Comment by snackerfork** [comment]
For anyone else having this problem, go to /home/deck/.local/share/Steam/ and delete the appcache and config folders, then restart the Steam Deck and log back in. That fixed it for me

**Comment by v-tron** [comment]
This also happens on Windows and deleting the folders doesn't fix the error.

**Comment by BadEugoogolizer** [comment]
Also experiencing this issue on SteamOS. Did everything suggested to no avail, but a couple hundred other titles had no errors being added even an hour before. It was adding about 120 NES titles from EmuDeck configured rom manager when the error first presented. Also trimmed the list of things to add to under 20 and no luck. It also started erroring on other lists.

However, it seems in my testing to be an error without an effect. I'm still seeing the error message every time, but the titles are being added to Steam as though there's no error.

**Comment by cbartondock** [comment]
I believe I have fixed this error in the upcoming version, it has to do with having titles that are purely numbers.

**Comment by cbartondock** [comment]
Closing as a duplicate of [Issue 278](https://github.com/SteamGridDB/steam-rom-manager/issues/278). Open a new issue if this isn't fixed after updating to 2.3.33 and (if necessary) removing and re-adding all added app entries.

**Comment by daalta** [comment]
Unfortunately I'm still experiencing this issue in 2.3.37.

Not sure what I should be trying to do and fix it, so please let me know if you have any troubleshooting instructions!

**Comment by cbartondock** [comment]
Appears to still be an issue in 2.3.37. Re-opening

**Comment by arickconley** [comment]
Just updated to 2.3.39 and still getting the "this.fileData.shortcuts.push is not a function" error.

**Comment by cbartondock** [comment]
Okay thanks for the update - i am unable to reproduce the bug so I am kind of shooting in the dark for the fix. Can you submit a bug report and dm the report ID to me (@lontanadascienza) on the discord?

**Comment by cbartondock** [comment]
This appears to be a bug in Heroic Bash Launcher, not SRM: https://github.com/redromnon/HeroicBashLauncher/issues/78

**Comment by cbartondock** [comment]
Should be fixed on HBL's side. If you still have this problem you most likely need to upgrade HBL (possibly after deleting shortcuts.vdf)

**Comment by redromnon** [comment]
Hey! The dev of HBL here. Do note that this fix will be implemented in the next release. 

> This appears to be a bug in Heroic Bash Launcher, not SRM: https://github.com/redromnon/HeroicBashLauncher/issues/78

I've linked the workflow build in the above mentioned issue for users eager to use it.

**Comment by redromnon** [comment]
Apparently it looks like some user got that same `TypeError: this.Filedata.shortcuts.push is not a function` again.
Here's a link to that Reddit post - https://www.reddit.com/r/SteamDeck/comments/vjwej3/heroic_bash_launcher_has_broken_steam_rom_manager/

Can someone please confirm if they've come across this error with HBL v2.7.5?
